# Setup
title:               Krishna
tagline:             'Agaram'
description:         'I hope what you are looking for finds you here.'
url:                 https://mathismusic.github.io/website2024
baseurl:             ''
paginate:            5
permalink:           pretty
# hosting on github
# theme:               lanyon

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.0
google_analytics_id: #UA-XXXX-Y
